import type {NextPage} from 'next'
import dynamic from 'next/dynamic'
import {GetStaticProps} from 'next'
import Head from 'next/head'
// import Tasks from "@/components/Tasks";
import {Box, Button, HStack, Stack} from "@chakra-ui/react";
import AddTaskInput from "@/components/AddTaskInput";
import DragTest from "@/components/DragTest";
import Column from "@/components/Column";
import {Status} from "@/graphql/generated/graphql";

const Tasks = dynamic(() => import("@/components/Tasks"), {ssr: false});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <HStack px={8} py={16} w='100vw'>
          <Column value="未着手" name={Status.NotStarted}>
            <AddTaskInput/>
            <Tasks/>
          </Column>
          <Column value="対応中" name={Status.Correspondence}>
            <DragTest/>
          </Column>
        </HStack>
      </main>
    </div>
  )
}

type Props = {}
export const getStaticProps: GetStaticProps<Props> = async (context) => {
  return {
    props: {},
  }
}
export default Home
