"""DB Init. Create tasks.

Revision ID: 96f40f79b17d
Revises: 
Create Date: 2022-05-25 14:07:56.313199

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 # by user
import uuid # by user


# revision identifiers, used by Alembic.
revision = '96f40f79b17d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), server_default='', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'correspondence', 'done', name='status'), server_default='not_started', nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
